/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_WarningStatus_.c
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#include "string.h"
#include "Rte_WarningStatus.h"


extern Rte_DE_float64 ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC;


const Rte_CDS_WarningStatus Rte_Instance_WarningStatus = {
&ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC
};

const Rte_CDS_WarningStatus * const Rte_Inst_WarningStatus = &Rte_Instance_WarningStatus;




float64 Rte_IRead_WarningStatus_ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC (void)
{
	return (Rte_Inst_WarningStatus)->ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC->value;
}
