/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/



/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	float64 value;
} Rte_DE_float64;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: Algorithm_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Algorithm_SWC
{
	/* Data Handles section*/
	Rte_DE_float64 *Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC;
	Rte_DE_float64 *Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC;
	Rte_DE_float64 *Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Algorithm_SWC;

/*********************************************************************
 * component data structure for SWC: SA_Speed_SWC 
 *********************************************************************/
typedef struct Rte_CDS_SA_Speed_SWC
{
	/* Data Handles section*/
	Rte_DE_float64 *SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC;
	Rte_DE_float64 *SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SA_Speed_SWC;

/*********************************************************************
 * component data structure for SWC: WarningStatus 
 *********************************************************************/
typedef struct Rte_CDS_WarningStatus
{
	/* Data Handles section*/
	Rte_DE_float64 *ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_WarningStatus;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
