/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Algorithm_SWC_.c
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#include "string.h"
#include "Rte_Algorithm_SWC.h"


Rte_DE_float64 Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC;
Rte_DE_float64 Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC;
Rte_DE_float64 Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC;

Rte_DE_float64 SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC;

const Rte_CDS_Algorithm_SWC Rte_Instance_Algorithm_SWC = {
&Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC,
&Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC,
&SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC
};

const Rte_CDS_Algorithm_SWC * const Rte_Inst_Algorithm_SWC = &Rte_Instance_Algorithm_SWC;




float64 Rte_IRead_Algorithm_SWC_Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC (void)
{
	return (Rte_Inst_Algorithm_SWC)->Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC->value;
}
void Rte_IWrite_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC (float64 EgoSpeed_AppSWC)
{
	(Rte_Inst_Algorithm_SWC)->Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC->value = EgoSpeed_AppSWC;
}
float64* Rte_IWriteRef_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC(void)
{
	return &(Rte_Inst_Algorithm_SWC)->Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC->value;
}
void Rte_IWrite_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC (float64 EgoSpeed_SASWC)
{
	(Rte_Inst_Algorithm_SWC)->Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC->value = EgoSpeed_SASWC;
}
float64* Rte_IWriteRef_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC(void)
{
	return &(Rte_Inst_Algorithm_SWC)->Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC->value;
}
