/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_WarningStatus.h
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#ifndef RTE_WARNINGSTATUS_H
#define RTE_WARNINGSTATUS_H

#include "Rte_WarningStatus_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_WarningStatus * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_WarningStatus * const Rte_Inst_WarningStatus;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_EgoSpeed_COM
 * Interface:	SRI_EgoSpeed_IOSWC
 * DataElement:	EgoSpeed_IOSWC
 * Runnable:	ALG_Warning
 *****************************************************/
extern float64 Rte_IRead_WarningStatus_ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC (void);
#ifndef IN_RTE_C
#define Rte_IRead_ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC() \
	Rte_IRead_WarningStatus_ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ALG_Warning
 * DataElement: EgoSpeed_IOSWC
 *****************************************************/
extern void ALG_Warning(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_WARNINGSTATUS_H */
