/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA_Speed_SWC_Type.h
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#ifndef RTE_SA_SPEED_SWC_TYPE_H
#define RTE_SA_SPEED_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define float64_LowerLimit  (0.0)
#define float64_UpperLimit (0.0)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SA_SPEED_SWC_TYPE_H */
