/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA_Speed_SWC_.c
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SA_Speed_SWC.h"


extern Rte_DE_float64 SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC;
Rte_DE_float64 SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC;

Rte_DE_float64 ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC;

const Rte_CDS_SA_Speed_SWC Rte_Instance_SA_Speed_SWC = {
&SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC,
&ALG_Warning_RP_EgoSpeed_COM_EgoSpeed_IOSWC
};

const Rte_CDS_SA_Speed_SWC * const Rte_Inst_SA_Speed_SWC = &Rte_Instance_SA_Speed_SWC;




void Rte_IWrite_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC (float64 EgoSpeed_IOSWC)
{
	(Rte_Inst_SA_Speed_SWC)->SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC->value = EgoSpeed_IOSWC;
}
float64* Rte_IWriteRef_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC(void)
{
	return &(Rte_Inst_SA_Speed_SWC)->SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC->value;
}
float64 Rte_IRead_SA_Speed_SWC_SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC (void)
{
	return (Rte_Inst_SA_Speed_SWC)->SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC->value;
}
