/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SA_Speed_SWC.h
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#ifndef RTE_SA_SPEED_SWC_H
#define RTE_SA_SPEED_SWC_H

#include "Rte_SA_Speed_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SA_Speed_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SA_Speed_SWC * const Rte_Inst_SA_Speed_SWC;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_EgoSpeed_SA
 * Interface:	SRI_EgoSpeed_IOSWC
 * DataElement:	EgoSpeed_IOSWC
 * Runnable:	SpeedTakeAction
 *****************************************************/
extern void Rte_IWrite_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC (float64 EgoSpeed_IOSWC);
#ifndef IN_RTE_C
#define Rte_IWrite_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC(RTEData) \
	Rte_IWrite_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC(RTEData)
#endif
extern float64* Rte_IWriteRef_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC() \
	Rte_IWriteRef_SA_Speed_SWC_SpeedTakeAction_PP_EgoSpeed_SA_EgoSpeed_IOSWC()
#endif

/*****************************************************
 * Port: 		RP_EgoSpeed_IO
 * Interface:	SRI_EgoSpeed_SASWC
 * DataElement:	EgoSpeed_SASWC
 * Runnable:	SpeedTakeAction
 *****************************************************/
extern float64 Rte_IRead_SA_Speed_SWC_SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC (void);
#ifndef IN_RTE_C
#define Rte_IRead_SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC() \
	Rte_IRead_SA_Speed_SWC_SpeedTakeAction_RP_EgoSpeed_IO_EgoSpeed_SASWC()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	SpeedTakeAction
 * DataElement: EgoSpeed_SASWC
 *****************************************************/
extern void SpeedTakeAction(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SA_SPEED_SWC_H */
