/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Algorithm_SWC.h
 * Generated on: Sat Mar 28 4:5:57 EET
 ********************************************************************/

#ifndef RTE_ALGORITHM_SWC_H
#define RTE_ALGORITHM_SWC_H

#include "Rte_Algorithm_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_Algorithm_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_Algorithm_SWC * const Rte_Inst_Algorithm_SWC;

/************************ application errors *************************/


/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_EgoSpeed_APP
 * Interface:	SRI_EgoSpeed_AppSWC
 * DataElement:	EgoSpeed_AppSWC
 * Runnable:	Runnable_ApplySpeed
 *****************************************************/
extern float64 Rte_IRead_Algorithm_SWC_Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC (void);
#ifndef IN_RTE_C
#define Rte_IRead_Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC() \
	Rte_IRead_Algorithm_SWC_Runnable_ApplySpeed_RP_EgoSpeed_APP_EgoSpeed_AppSWC()
#endif

/*****************************************************
 * Port: 		PP_EgoSpeed_APP
 * Interface:	SRI_EgoSpeed_AppSWC
 * DataElement:	EgoSpeed_AppSWC
 * Runnable:	Runnable_ReceiveCanFram
 *****************************************************/
extern void Rte_IWrite_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC (float64 EgoSpeed_AppSWC);
#ifndef IN_RTE_C
#define Rte_IWrite_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC(RTEData) \
	Rte_IWrite_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC(RTEData)
#endif
extern float64* Rte_IWriteRef_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC() \
	Rte_IWriteRef_Algorithm_SWC_Runnable_ReceiveCanFram_PP_EgoSpeed_APP_EgoSpeed_AppSWC()
#endif

/*****************************************************
 * Port: 		PP_EgoSpeed_SA
 * Interface:	SRI_EgoSpeed_SASWC
 * DataElement:	EgoSpeed_SASWC
 * Runnable:	Runnable_ApplySpeed
 *****************************************************/
extern void Rte_IWrite_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC (float64 EgoSpeed_SASWC);
#ifndef IN_RTE_C
#define Rte_IWrite_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC(RTEData) \
	Rte_IWrite_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC(RTEData)
#endif
extern float64* Rte_IWriteRef_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC() \
	Rte_IWriteRef_Algorithm_SWC_Runnable_ApplySpeed_PP_EgoSpeed_SA_EgoSpeed_SASWC()
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Runnable_ReceiveCanFram
 * Period:		0.01
 *****************************************************/
extern void Runnable_ReceiveCanFram(void);

/*****************************************************
 * Runnable: 	Runnable_ApplySpeed
 * DataElement: EgoSpeed_AppSWC
 *****************************************************/
extern void Runnable_ApplySpeed(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_ALGORITHM_SWC_H */
